repo_name: udayraj123/OMRChecker
repo_url: https://github.com/udayraj123/OMRChecker
site_name: OMRChecker
site_url: https://udayraj123.github.io/OMRChecker/ # Trailing slash is recommended

# Paths relative to docs/ folder
nav:
  - Home: index.md
  - Guides:
      - User Guide: "v2/User-Guide.md"
      - Templates: "v2/About-Templates.md"
      - Config: "v2/About-Config.md"
      - Evaluation: "v2/About-Evaluation.md"
      - For Contributors: "v1/For Contributors.md"
      - v1 Guide:
          - User Guide: "v1/User-Guide.md"
          - Templates: "v1/About-Templates.md"
          - TODOs: "v1/TODOs.md"
  - Visualizations:
      - Diagrams: "v1/Diagrams.md"
      - Rich Visuals: "v1/Rich Visuals.md"

plugins:
  - search
  # - mkdocstrings // TODO: enable mkdocstrings plugin
  - macros:
      module_name: mkdocs
      on_undefined: strict
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ""
      css_dir: css
      javascript_dir: js
      canonical_version: null
      version_selector: true

validation:
  # https://github.com/squidfunk/mkdocs-material/discussions/5897
  links:
    absolute_links: relative_to_docs

theme:
  name: material
  custom_dir: docs/overrides

  features:
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.top

  icon:
    logo: omrchecker-icon
    favicon: images/favicon.png
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  highlightjs: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: ยง
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      linenums: true
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.snippets

  # # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  #     options:
  #       custom_icons:
  #         - overrides/.icons

extra_css:
  - assets/stylesheets/extra.css

extra:
  generator: false
  version:
    # mike makes it easy to deploy multiple versions of your project documentation.
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/udayraj123
      name: udayraj123 on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/udayraj123/
      name: udayraj123 on LinkedIn
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/udayraj123
      name: udayraj123 on X
  CDN_PREFIX: "https://raw.githubusercontent.com/wiki/Udayraj123/OMRChecker"

copyright: Copyright &copy; 2025 udayraj123
