/**
 * Python-TypeScript Parity Tests
 * 
 * These tests verify that TypeScript implementations produce identical results
 * to their Python counterparts. Test fixtures are generated by running Python
 * implementations and capturing outputs.
 * 
 * Generate fixtures:
 *   uv run python scripts/generate_parity_fixtures.py
 * 
 * Run tests:
 *   npm run test:unit -- parity
 */

import { describe, it, expect } from 'vitest';
import { MathUtils } from '../../src/utils/math';
import fixtures from './fixtures.json';

describe('Python-TypeScript Parity Tests', () => {
  describe('MathUtils Parity', () => {
    describe('distance()', () => {
      fixtures.math.distance.forEach((fixture, index) => {
        it(`should match Python output for test case ${index + 1}`, () => {
          const { p1, p2 } = fixture.input;
          const result = MathUtils.distance(p1, p2);
          expect(result).toBeCloseTo(fixture.output, 10); // 10 decimal places
        });
      });
    });

    describe('addPoints()', () => {
      fixtures.math.add_points.forEach((fixture, index) => {
        it(`should match Python output for test case ${index + 1}`, () => {
          const { p1, p2 } = fixture.input;
          const result = MathUtils.addPoints(p1, p2);
          expect(result).toEqual(fixture.output);
        });
      });
    });

    describe('subtractPoints()', () => {
      fixtures.math.subtract_points.forEach((fixture, index) => {
        it(`should match Python output for test case ${index + 1}`, () => {
          const { p1, p2 } = fixture.input;
          const result = MathUtils.subtractPoints(p1, p2);
          expect(result).toEqual(fixture.output);
        });
      });
    });

    describe('angle()', () => {
      fixtures.math.angle.forEach((fixture, index) => {
        it(`should match Python output for test case ${index + 1}`, () => {
          const { p1, p2, p0 } = fixture.input;
          const result = MathUtils.angle(p1, p2, p0);
          expect(result).toBeCloseTo(fixture.output, 10);
        });
      });
    });

    describe('checkCollinearPoints()', () => {
      fixtures.math.check_collinear_points.forEach((fixture, index) => {
        it(`should match Python output for test case ${index + 1}`, () => {
          const { p1, p2, p3 } = fixture.input;
          const result = MathUtils.checkCollinearPoints(p1, p2, p3);
          expect(result).toBe(fixture.output);
        });
      });
    });
  });

  describe('Checksum Parity', () => {
    describe('calculate_checksum()', () => {
      fixtures.checksum.calculate_checksum.forEach((fixture, index) => {
        it(`should match Python output for ${fixture.input.algorithm} hash (case ${index + 1})`, async () => {
          const { data, algorithm } = fixture.input;
          
          // Use Node crypto module (works in both Node and jsdom)
          const crypto = await import('crypto');
          const hash = crypto.createHash(algorithm);
          hash.update(data);
          const result = hash.digest('hex');
          
          expect(result).toBe(fixture.output);
        });
      });
    });
  });

  describe('Metadata', () => {
    it('should have valid fixture metadata', () => {
      expect(fixtures.metadata).toBeDefined();
      expect(fixtures.metadata.generated_by).toBe('scripts/generate_parity_fixtures.py');
      expect(fixtures.metadata.python_version).toBeTruthy();
    });

    it('should have all expected test groups', () => {
      expect(fixtures.math).toBeDefined();
      expect(fixtures.checksum).toBeDefined();
      
      // Math test counts
      expect(fixtures.math.distance.length).toBeGreaterThan(0);
      expect(fixtures.math.add_points.length).toBeGreaterThan(0);
      expect(fixtures.math.subtract_points.length).toBeGreaterThan(0);
      expect(fixtures.math.angle.length).toBeGreaterThan(0);
      expect(fixtures.math.check_collinear_points.length).toBeGreaterThan(0);
      
      // Checksum test counts
      expect(fixtures.checksum.calculate_checksum.length).toBeGreaterThan(0);
    });
  });
});
