"""Constants package for OMRChecker."""

from src.constants.image_processing import (
    APPROX_POLY_EPSILON_FACTOR,
    CANNY_THRESHOLD_HIGH,
    CANNY_THRESHOLD_LOW,
    CONTOUR_THICKNESS_STANDARD,
    MIN_PAGE_AREA,
    PIXEL_VALUE_MAX,
    THRESH_PAGE_TRUNCATE_HIGH,
    THRESH_PAGE_TRUNCATE_SECONDARY,
    TOP_CONTOURS_COUNT,
)

__all__ = [
    "APPROX_POLY_EPSILON_FACTOR",
    "CANNY_THRESHOLD_HIGH",
    "CANNY_THRESHOLD_LOW",
    "CONTOUR_THICKNESS_STANDARD",
    "MIN_PAGE_AREA",
    "PIXEL_VALUE_MAX",
    "THRESH_PAGE_TRUNCATE_HIGH",
    "THRESH_PAGE_TRUNCATE_SECONDARY",
    "TOP_CONTOURS_COUNT",
]
