/**
 * Configuration schema validation for OMRChecker
 *
 * TypeScript port of src/schemas/config_schema.py
 * Uses AJV with Draft 2020-12 support and shared definitions from common.ts
 */

import {
  commonSchemaDefinitions,
  createSchemaValidator,
  formatValidationErrors,
  ValidationResult,
} from './common';
import { OUTPUT_MODES, SUPPORTED_PROCESSOR_NAMES } from '../utils/constants';

// DRY: Integer range property factory (used 14 times in thresholding section)
function integerRange(
  min: number,
  max: number,
  description: string
): Record<string, unknown> {
  return {
    description,
    type: 'integer' as const,
    minimum: min,
    maximum: max,
  };
}

// DRY: Number range property factory
function numberRange(
  min: number,
  max: number,
  description: string
): Record<string, unknown> {
  return {
    description,
    type: 'number' as const,
    minimum: min,
    maximum: max,
  };
}

// Config JSON Schema (Draft 2020-12)
const CONFIG_SCHEMA = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://github.com/Udayraj123/OMRChecker/tree/master/src/schemas/config-schema.json',
  $defs: {
    ...commonSchemaDefinitions,
  },
  title: 'Config Schema',
  description: 'OMRChecker config schema for custom tuning',
  type: 'object',
  allOf: [
    {
      // Note: Using additionalProperties: false is too strict for partial configs
      properties: {
        path: {
          description: 'The path to the config file',
          type: 'string',
        },
        thresholding: {
          description:
            'The values used in the core algorithm of OMRChecker',
          type: 'object',
          additionalProperties: false,
          properties: {
            MIN_GAP_TWO_BUBBLES: integerRange(
              10,
              100,
              'Minimum difference between all mean values of the bubbles'
            ),
            MIN_JUMP: integerRange(
              10,
              100,
              'Minimum difference between consecutive elements'
            ),
            MIN_JUMP_STD: integerRange(1, 50, 'The MIN_JUMP for the standard deviation plot'),
            MIN_JUMP_SURPLUS_FOR_GLOBAL_FALLBACK: integerRange(
              0,
              20,
              'Added to jump value for fallback threshold'
            ),
            GLOBAL_THRESHOLD_MARGIN: integerRange(
              0,
              20,
              'Determines if global threshold is too close to lower bubbles'
            ),
            JUMP_DELTA: integerRange(10, 100, 'Deprecated, used only in plots'),
            JUMP_DELTA_STD: integerRange(
              1,
              50,
              'Minimum delta for jump in std plot'
            ),
            CONFIDENT_JUMP_SURPLUS_FOR_DISPARITY: integerRange(
              0,
              100,
              'Distinguish safe vs underconfident detections'
            ),
            GLOBAL_PAGE_THRESHOLD: integerRange(
              0,
              255,
              'Starting value before applying local outlier threshold'
            ),
            GLOBAL_PAGE_THRESHOLD_STD: integerRange(
              0,
              60,
              'Starting value for standard deviation threshold'
            ),
            GAMMA_LOW: numberRange(
              0,
              1,
              'Used for creating darker image for enhanced line detection'
            ),
          },
        },
        outputs: {
          description:
            'The configuration related to the outputs generated by OMRChecker',
          type: 'object',
          additionalProperties: false,
          properties: {
            output_mode: {
              type: 'string',
              enum: Object.values(OUTPUT_MODES),
              description:
                'The output mode for the OMRChecker. Supported: default, moderation, setLayout',
            },
            display_image_dimensions: {
              $ref: '#/$defs/two_positive_integers',
              description:
                'The dimensions (width, height) for images displayed during execution',
            },
            show_logs_by_type: {
              description: 'The toggles for enabling logs per level',
              type: 'object',
              additionalProperties: false,
              properties: {
                critical: { type: 'boolean' },
                error: { type: 'boolean' },
                warning: { type: 'boolean' },
                info: { type: 'boolean' },
                debug: { type: 'boolean' },
              },
            },
            show_image_level: integerRange(
              0,
              6,
              'Toggle level for showing debug images'
            ),
            save_image_level: integerRange(
              0,
              6,
              'Toggle level for saving debug images'
            ),
            colored_outputs_enabled: {
              description: 'Shows colored outputs with small performance toll',
              type: 'boolean',
            },
            save_detections: {
              description: 'Saves detection outputs with small performance toll',
              type: 'boolean',
            },
            save_image_metrics: {
              description: 'Exports confidence metrics for deeper analysis',
              type: 'boolean',
            },
            show_confidence_metrics: {
              description: 'Toggle for enabling confidence metrics calculation',
              type: 'boolean',
            },
            filter_out_multimarked_files: {
              description:
                'Moves files with multi-marked responses for manual checking',
              type: 'boolean',
            },
            file_grouping: {
              description:
                'Configuration for organizing processed files with dynamic patterns',
              type: 'object',
              properties: {
                enabled: {
                  description: 'Enable automatic file organization',
                  type: 'boolean',
                  default: false,
                },
                default_pattern: {
                  description: 'Default pattern for files not matching any rule',
                  type: 'string',
                  default: 'ungrouped/{original_name}',
                },
                rules: {
                  description: 'List of grouping rules (evaluated by priority)',
                  type: 'array',
                  items: {
                    type: 'object',
                    required: ['name', 'priority', 'destination_pattern', 'matcher'],
                    properties: {
                      name: {
                        description: 'Rule name for logging',
                        type: 'string',
                      },
                      priority: {
                        description: 'Rule priority (lower = higher priority)',
                        type: 'integer',
                        minimum: 0,
                      },
                      destination_pattern: {
                        description: 'Full path pattern with {field} placeholders',
                        type: 'string',
                      },
                      action: {
                        description: 'Action to perform (symlink or copy)',
                        enum: ['symlink', 'copy'],
                        default: 'symlink',
                      },
                      collision_strategy: {
                        description: 'How to handle filename collisions',
                        enum: ['skip', 'increment', 'overwrite'],
                        default: 'skip',
                      },
                      matcher: {
                        description: 'Pattern matcher using format string + regex',
                        type: 'object',
                        required: ['formatString', 'matchRegex'],
                        properties: {
                          formatString: {
                            description: 'Format string with {field} placeholders',
                            type: 'string',
                          },
                          matchRegex: {
                            description: 'Regex pattern to match formatted string',
                            type: 'string',
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
            show_preprocessors_diff: {
              description:
                'Shows preview of processed image for every preprocessor',
              oneOf: [
                {
                  type: 'object',
                  patternProperties: {
                    [`^(${SUPPORTED_PROCESSOR_NAMES.join('|')})$`]: {
                      type: 'boolean',
                    },
                  },
                },
                { type: 'boolean' },
              ],
            },
          },
        },
        processing: {
          description: 'The configuration related to processing settings',
          type: 'object',
          additionalProperties: false,
          properties: {
            max_parallel_workers: integerRange(
              1,
              16,
              'Number of worker threads for parallel processing'
            ),
          },
        },
        ml: {
          description:
            'The configuration related to ML-based detection and training',
          type: 'object',
          additionalProperties: false,
          properties: {
            enabled: {
              description: 'Enable ML-based detection features',
              type: 'boolean',
            },
            model_path: {
              description: 'Path to trained YOLO model for bubble detection',
              type: ['string', 'null'],
            },
            confidence_threshold: numberRange(
              0.0,
              1.0,
              'Minimum confidence threshold for ML predictions'
            ),
            use_for_low_confidence_only: {
              description: 'Use ML only for low-confidence traditional detections',
              type: 'boolean',
            },
            collect_training_data: {
              description:
                'Collect high-confidence detections for ML training',
              type: 'boolean',
            },
            min_training_confidence: numberRange(
              0.0,
              1.0,
              'Minimum confidence score to include in training data'
            ),
            training_data_dir: {
              description: 'Directory to store bubble training data',
              type: 'string',
            },
            model_output_dir: {
              description: 'Directory to store trained models',
              type: 'string',
            },
            field_block_detection_enabled: {
              description: 'Enable Stage 1 field block detection',
              type: 'boolean',
            },
            field_block_model_path: {
              description:
                'Path to trained YOLO model for field block detection',
              type: ['string', 'null'],
            },
            field_block_confidence_threshold: numberRange(
              0.0,
              1.0,
              'Minimum confidence threshold for field block detection'
            ),
            collect_field_block_data: {
              description: 'Collect field block data for ML training',
              type: 'boolean',
            },
            field_block_dataset_dir: {
              description: 'Directory to store field block training data',
              type: 'string',
            },
            bubble_dataset_dir: {
              description: 'Directory to store bubble training data',
              type: 'string',
            },
            shift_detection: {
              description:
                'Configuration for ML-based field block shift detection',
              type: 'object',
              additionalProperties: false,
              properties: {
                enabled: {
                  description: 'Enable ML-based shift detection',
                  type: 'boolean',
                },
                global_max_shift_pixels: {
                  description: 'Global maximum shift allowed in pixels',
                  type: 'integer',
                  minimum: 0,
                },
                per_block_max_shift_pixels: {
                  description: 'Per-block maximum shift overrides',
                  type: 'object',
                  additionalProperties: {
                    type: 'integer',
                    minimum: 0,
                  },
                },
                confidence_reduction_min: numberRange(
                  0.0,
                  1.0,
                  'Minimum confidence reduction when shift causes mismatch'
                ),
                confidence_reduction_max: numberRange(
                  0.0,
                  1.0,
                  'Maximum confidence reduction for severe mismatches'
                ),
                bubble_mismatch_threshold: {
                  description: 'Flag mismatches if more than this many bubbles differ',
                  type: 'integer',
                  minimum: 0,
                },
                field_mismatch_threshold: {
                  description: 'Flag mismatches if this many or more fields differ',
                  type: 'integer',
                  minimum: 0,
                },
              },
            },
            fusion_enabled: {
              description:
                'Enable detection fusion between traditional and ML methods',
              type: 'boolean',
            },
            fusion_strategy: {
              description:
                'Strategy for fusing traditional and ML detections',
              type: 'string',
              enum: [
                'confidence_weighted',
                'ml_fallback',
                'traditional_primary',
                'ml_only',
              ],
            },
            discrepancy_threshold: numberRange(
              0.0,
              1.0,
              'Threshold for flagging discrepancies between traditional and ML'
            ),
          },
        },
        visualization: {
          description: 'Configuration for workflow visualization and debugging',
          type: 'object',
          additionalProperties: false,
          properties: {
            enabled: {
              description: 'Enable workflow visualization',
              type: 'boolean',
            },
            capture_processors: {
              description:
                'List of processor names to capture or ["all"] for all',
              type: 'array',
              items: { type: 'string' },
            },
            capture_frequency: {
              description: 'When to capture images',
              type: 'string',
              enum: ['always', 'on_change'],
            },
            include_colored: {
              description: 'Capture colored images in addition to grayscale',
              type: 'boolean',
            },
            max_image_width: integerRange(
              100,
              4000,
              'Maximum width for captured images in pixels'
            ),
            embed_images: {
              description:
                'Embed images in HTML (true) or reference externally (false)',
              type: 'boolean',
            },
            export_format: {
              description: 'Format for exporting visualizations',
              type: 'string',
              enum: ['html', 'json'],
            },
            output_dir: {
              description: 'Directory to save visualizations',
              type: 'string',
            },
            auto_open_browser: {
              description: 'Automatically open visualization in browser',
              type: 'boolean',
            },
          },
        },
      },
    },
    // Conditional validation: show_image_level > 0 requires max_parallel_workers = 1
    // Note: This condition only applies when show_image_level is explicitly set > 0
    {
      if: {
        properties: {
          outputs: {
            type: 'object',
            properties: {
              show_image_level: {
                type: 'integer',
                minimum: 1, // Only trigger when > 0
              },
            },
            required: ['show_image_level'],
          },
        },
        required: ['outputs'],
      },
      then: {
        properties: {
          processing: {
            type: 'object',
            properties: {
              max_parallel_workers: {
                const: 1,
              },
            },
          },
        },
      },
    },
  ],
};

// DRY: Reusable validator wrapper
function createConfigValidator() {
  const ajv = createSchemaValidator();
  const validate = ajv.compile(CONFIG_SCHEMA);

  return (data: unknown): ValidationResult => ({
    valid: !!validate(data),
    errors: formatValidationErrors(validate.errors),
  });
}

// Export singleton validator instance
export const validateConfig = createConfigValidator();

// Export schema for testing/inspection
export { CONFIG_SCHEMA };

