name: Deploy MkDocs

on:
  push:
    branches:
      - master
      - dev
      - feature/mkdocs-debug # temp

  pull_request:
    branches: [master]

permissions:
  contents: write

env:
  IS_NOT_A_FORK: ${{ github.event.pull_request.head.repo.fork == false }}
  IS_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}
  IS_PUSH: ${{ github.event_name == 'push' }}
  BRANCH_NAME: ${{ github.ref_name }}
  IS_MASTER: ${{ BRANCH_NAME == 'master' }}
  IS_DEV: ${{ BRANCH_NAME == 'dev' }}
  MIKE_DEPLOY_VERSION: ${{ $IS_MASTER && '1.x' || ($IS_DEV && '2.x' || '$BRANCH_NAME') }}

jobs:
  deploy:
    if: ${{ ($IS_PUSH || $IS_NOT_A_FORK) && $MIKE_DEPLOY_VERSION != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        uses: ./.github/actions/setup-git-config
        with:
          name: github-actions[bot]
          email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Python 3.13 with uv
        uses: ./.github/actions/setup-python-with-uv
        with:
          python-version: 3.13

      - name: Generate cache id
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Save cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: mkdocs-material-

      - run: uv run mike deploy "$MIKE_DEPLOY_VERSION"
