name: Docker
# Only run Docker workflow if Docker-related files have changed

on:
  push:
    branches: [master]
    paths:
      - Dockerfile
      - .devcontainer/Dockerfile
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  lint-devcontainer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: .devcontainer/Dockerfile

  build:
    runs-on: ubuntu-latest

    needs: lint
    if: ${{ success() }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          tags: latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-devcontainer:
    runs-on: ubuntu-latest

    needs: lint-devcontainer
    if: ${{ success() }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: false
          tags: latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
