name: Pyright

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  type-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.13"]

    steps:
      - uses: jakebailey/pyright-action@v2
        with:
          python-version: ${{ matrix.python-version }}
